// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ScuolaAPIServer.Data;

#nullable disable

namespace ScuolaAPIServer.Migrations
{
    [DbContext(typeof(ScuolaDbContext))]
    [Migration("20251215111119_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CorsoProfessore", b =>
                {
                    b.Property<int>("CorsiId")
                        .HasColumnType("int");

                    b.Property<int>("ProfessoriId")
                        .HasColumnType("int");

                    b.HasKey("CorsiId", "ProfessoriId");

                    b.HasIndex("ProfessoriId");

                    b.ToTable("CorsoProfessore");
                });

            modelBuilder.Entity("CorsoStudente", b =>
                {
                    b.Property<int>("CorsiId")
                        .HasColumnType("int");

                    b.Property<int>("StudentiId")
                        .HasColumnType("int");

                    b.HasKey("CorsiId", "StudentiId");

                    b.HasIndex("StudentiId");

                    b.ToTable("CorsoStudente");
                });

            modelBuilder.Entity("ScuolaAPIServer.Models.Corso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Codice")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Corsi");
                });

            modelBuilder.Entity("ScuolaAPIServer.Models.Professore", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cognome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Professori");
                });

            modelBuilder.Entity("ScuolaAPIServer.Models.Studente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cognome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Età")
                        .HasColumnType("int");

                    b.Property<string>("Matricola")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Matricola")
                        .IsUnique();

                    b.ToTable("Studenti");
                });

            modelBuilder.Entity("CorsoProfessore", b =>
                {
                    b.HasOne("ScuolaAPIServer.Models.Corso", null)
                        .WithMany()
                        .HasForeignKey("CorsiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ScuolaAPIServer.Models.Professore", null)
                        .WithMany()
                        .HasForeignKey("ProfessoriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CorsoStudente", b =>
                {
                    b.HasOne("ScuolaAPIServer.Models.Corso", null)
                        .WithMany()
                        .HasForeignKey("CorsiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ScuolaAPIServer.Models.Studente", null)
                        .WithMany()
                        .HasForeignKey("StudentiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
