// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ScuolaAPIServer.Data;

#nullable disable

namespace ScuolaAPIServer.Migrations
{
    [DbContext(typeof(ScuolaDbContext))]
    partial class ScuolaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ScuolaAPIServer.Models.Corso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Codice")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Corsi");
                });

            modelBuilder.Entity("ScuolaAPIServer.Models.Professore", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cognome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Professori");
                });

            modelBuilder.Entity("ScuolaAPIServer.Models.ProfessoreCorso", b =>
                {
                    b.Property<int>("ProfessoreId")
                        .HasColumnType("int");

                    b.Property<int>("CorsoId")
                        .HasColumnType("int");

                    b.HasKey("ProfessoreId", "CorsoId");

                    b.HasIndex("CorsoId");

                    b.ToTable("ProfessoreCorso");
                });

            modelBuilder.Entity("ScuolaAPIServer.Models.Studente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cognome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Età")
                        .HasColumnType("int");

                    b.Property<string>("Matricola")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Studenti");
                });

            modelBuilder.Entity("ScuolaAPIServer.Models.StudenteCorso", b =>
                {
                    b.Property<int>("StudenteId")
                        .HasColumnType("int");

                    b.Property<int>("CorsoId")
                        .HasColumnType("int");

                    b.HasKey("StudenteId", "CorsoId");

                    b.HasIndex("CorsoId");

                    b.ToTable("StudenteCorso");
                });

            modelBuilder.Entity("ScuolaAPIServer.Models.ProfessoreCorso", b =>
                {
                    b.HasOne("ScuolaAPIServer.Models.Corso", "Corso")
                        .WithMany("ProfessoreCorsi")
                        .HasForeignKey("CorsoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ScuolaAPIServer.Models.Professore", "Professore")
                        .WithMany("ProfessoreCorsi")
                        .HasForeignKey("ProfessoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Corso");

                    b.Navigation("Professore");
                });

            modelBuilder.Entity("ScuolaAPIServer.Models.StudenteCorso", b =>
                {
                    b.HasOne("ScuolaAPIServer.Models.Corso", "Corso")
                        .WithMany("StudenteCorsi")
                        .HasForeignKey("CorsoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ScuolaAPIServer.Models.Studente", "Studente")
                        .WithMany("StudenteCorsi")
                        .HasForeignKey("StudenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Corso");

                    b.Navigation("Studente");
                });

            modelBuilder.Entity("ScuolaAPIServer.Models.Corso", b =>
                {
                    b.Navigation("ProfessoreCorsi");

                    b.Navigation("StudenteCorsi");
                });

            modelBuilder.Entity("ScuolaAPIServer.Models.Professore", b =>
                {
                    b.Navigation("ProfessoreCorsi");
                });

            modelBuilder.Entity("ScuolaAPIServer.Models.Studente", b =>
                {
                    b.Navigation("StudenteCorsi");
                });
#pragma warning restore 612, 618
        }
    }
}
