// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication1.Data;

#nullable disable

namespace WebApplication1.Migrations
{
    [DbContext(typeof(ScuolaContext))]
    partial class ScuolaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CorsoDocente", b =>
                {
                    b.Property<int>("DocentiId")
                        .HasColumnType("int");

                    b.Property<int>("corsiId")
                        .HasColumnType("int");

                    b.HasKey("DocentiId", "corsiId");

                    b.HasIndex("corsiId");

                    b.ToTable("CorsoDocente");
                });

            modelBuilder.Entity("CorsoStudente", b =>
                {
                    b.Property<int>("CorsiId")
                        .HasColumnType("int");

                    b.Property<int>("studentiId")
                        .HasColumnType("int");

                    b.HasKey("CorsiId", "studentiId");

                    b.HasIndex("studentiId");

                    b.ToTable("CorsoStudente");
                });

            modelBuilder.Entity("WebApplication1.Models.Corso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Titolo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("codiceCorso")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Corsi");
                });

            modelBuilder.Entity("WebApplication1.Models.Docente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Docente");
                });

            modelBuilder.Entity("WebApplication1.Models.Studente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cognome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Eta")
                        .HasColumnType("int");

                    b.Property<string>("Matricola")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Matricola")
                        .IsUnique();

                    b.ToTable("Studenti");
                });

            modelBuilder.Entity("CorsoDocente", b =>
                {
                    b.HasOne("WebApplication1.Models.Docente", null)
                        .WithMany()
                        .HasForeignKey("DocentiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApplication1.Models.Corso", null)
                        .WithMany()
                        .HasForeignKey("corsiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CorsoStudente", b =>
                {
                    b.HasOne("WebApplication1.Models.Corso", null)
                        .WithMany()
                        .HasForeignKey("CorsiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApplication1.Models.Studente", null)
                        .WithMany()
                        .HasForeignKey("studentiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
