/*
--CREAZIONE NUOVO DATABASE
CREATE DATABASE NEGOZIODB;
 --SERVE A SEPARARE I COMANDI COSì CHE NON VADANO IN CONTEMPORANEA
--USO IL DB

USE NEGOZIODB;


CREATE TABLE CLIENTI(
ID INT PRIMARY KEY IDENTITY(1,1), --AUTOINCREMENT DI 1 IN ID
NOME NVARCHAR(50) NOT NULL,
EMAIL NVARCHAR(50) NOT NULL UNIQUE, 
DATA_REGISTRAZIONE DATE DEFAULT GETDATE(), --SETTA LA DATA A NOW CON GETDATE()
TITOLO_DI_STUDIO_ID INT NOT NULL
);

CREATE TABLE TITOLI_STUDIO(
ID INT PRIMARY KEY IDENTITY(1,1),
TDS NVARCHAR(50) NOT NULL
);


--MODIFICA PER AGGIUNTA FK A TABELLA CLIENTE
ALTER TABLE CLIENTI ADD CONSTRAINT FK_CLI_TDS
     FOREIGN KEY (TITOLO_DI_STUDIO_ID) REFERENCES TITOLI_STUDIO (ID)
     
CREATE TABLE PRODOTTI(
ID INT PRIMARY KEY IDENTITY(1,1),
NOME_PRODOTTO NVARCHAR(50) NOT NULL,
PREZZO DECIMAL(10,2) NOT NULL CHECK(PREZZO > 0),  --IN DECIMAL I DUE NUMERI INDICANO10 CARATTERI E 2 DECIMALI, CHECK è UNA FUNZIONE CHE CI PERMETTE DI FARE UN CONTROLLO SU VALORE INSERITO
GIACENZA INT  NOT NULL
);


CREATE TABLE ORDINI(
ID INT PRIMARY KEY IDENTITY(1,1),
DATA_ORDINE DATETIME DEFAULT SYSDATETIME(), -- DATA DI SISTEMA ATTUALE
NUM_COLLI INT,
TOTALE DECIMAL(10,2),
INDIRIZZO_SPEDIZIONE NVARCHAR(100) NOT NULL,
CLIENTI_ID INT NOT NULL ,
PUNTO_VENDITA_ID NVARCHAR(100),
CONSTRAINT FK_ORD_CLI FOREIGN KEY (CLIENTI_ID) REFERENCES CLIENTI(ID)
);

CREATE TABLE DETTAGLIORDINE(
ID INT PRIMARY KEY IDENTITY(1,1),
QUANTITA INT NOT NULL,
PREZZOU  DECIMAL(10,2) NOT NULL,
ID_ORDINE INT NOT NULL,
ID_PROD INT NOT NULL,
CONSTRAINT FK_ORD_DETT FOREIGN KEY (ID_ORDINE) REFERENCES ORDINI(ID),
CONSTRAINT FK_PROD_DETT FOREIGN KEY (ID_PROD) REFERENCES PRODOTTI(ID)
);
*/
/*
INSERT INTO TITOLI_STUDIO (TDS) VALUES
('Licenza Media'),
('Diploma'),
('Laurea Triennale'),
('Laurea Magistrale'),
('Master');


INSERT INTO CLIENTI(nome,email,TITOLO_DI_STUDIO_ID) VALUES('Luca Bianchi', 'luca.bianchi@example.com', 1),
('Sara Verdi', 'sara.verdi@example.com', 2),
('Marco Esposito', 'marco.esposito@example.com', 3),
('Giulia Romano', 'giulia.romano@example.com', 4),
('Antonio Serra', 'antonio.serra@example.com', 5);

INSERT INTO PRODOTTI (NOME_PRODOTTO, PREZZO, GIACENZA) VALUES('PRODOTTO1', 50.12,10 ),('PRODOTTO2', 38.47,55 ),
('PRODOTTO3', 450.12,10 ),('PRODOTTO4', 18.17,28 ),('PRODOTTO5', 150.92,100 ),('PRODOTTO6', 62.17,30 ),
('PRODOTTO7', 22.10,44 ),('PRODOTTO8', 138.47,15 );


SELECT * FROM PRODOTTI;

SELECT * FROM CLIENTI;
INSERT INTO ORDINI(NUM_COLLI,TOTALE,INDIRIZZO_SPEDIZIONE,PUNTO_VENDITA_ID,CLIENTI_ID) VALUES (11,850.43,'VIA 1 ,X, Y, Z','NEGOZIO 1',3),(11,850.43,'VIA 1 ,X, Y, Z','NEGOZIO 2',4),(11,743.43,'VIA 1 ,X, Y, Z','NEGOZIO 3',6),(11,98.23,'VIA 1 ,X, Y, Z','NEGOZIO 4',7),(11,195.11,'VIA 1 ,X, Y, Z','NEGOZIO 5',5);

INSERT INTO DETTAGLIORDINE (QUANTITA, PREZZOU, ID_PROD, ID_ORDINE)
VALUES (1, 299.99, 7, 3),(5, 1499.99, 6, 4),(4, 1899.99, 5, 5),(10, 99.99, 4, 6),(6, 1299.99, 3, 7);


SELECT * FROM CLIENTI C JOIN TITOLI_STUDIO T ON C.TITOLO_DI_STUDIO_ID = T.ID;

CREATE VIEW v_clienti_titoli 
AS
SELECT C.* , T.TDS FROM CLIENTI C JOIN TITOLI_STUDIO T ON C.TITOLO_DI_STUDIO_ID = T.ID;

SELECT * FROM v_clienti_titoli;

CREATE VIEW v_clienti_ordini
AS
SELECT O.ID,O.DATA_ORDINE,O.INDIRIZZO_SPEDIZIONE,O.NUM_COLLI,O.PUNTO_VENDITA_ID,O.TOTALE,C.EMAIL, C.NOME FROM ORDINI O JOIN CLIENTI C ON O.CLIENTI_ID = C.ID;

SELECT * FROM DETTAGLIORDINE ORDER BY DETTAGLIORDINE.ID_ORDINE;

SELECT D.ID,D.PREZZOU,D.QUANTITA,D.ID_PROD,O.ID,O.DATA_ORDINE,O.CLIENTI_ID,O.INDIRIZZO_SPEDIZIONE,O.NUM_COLLI,O.PUNTO_VENDITA_ID,O.TOTALE,C.NOME FROM DETTAGLIORDINE D JOIN ORDINI O ON D.ID_ORDINE = O.ID JOIN CLIENTI C ON C.ID = O.CLIENTI_ID ORDER BY O.ID; 


--select d.ID_ORDINE, SUM(QUANTITA * PREZZOU)  AS 'totale dettagli ordine' from DETTAGLIORDINE d GROUP BY d.ID_ORDINE;
UPDATE ORDINI
SET ORDINI.TOTALE = (
SELECT
SUM(QUANTITA * PREZZOU) AS TotaleOrdine
FROM DETTAGLIORDINE
where ID_ORDINE = 2
GROUP BY ID_ORDINE)


SELECT P.NOME_PRODOTTO, SUM(D.QUANTITA) AS TOTALE_RICHIESTE FROM DETTAGLIORDINE D JOIN PRODOTTI P ON P.ID = D.ID_PROD GROUP BY P.NOME_PRODOTTO ORDER BY TOTALE_RICHIESTE DESC;


SELECT P.NOME_PRODOTTO, SUM(D.QUANTITA) AS TOTALE_RICHIESTE
FROM DETTAGLIORDINE D
JOIN PRODOTTI P ON P.ID = D.ID_PROD
GROUP BY P.NOME_PRODOTTO
HAVING SUM(D.QUANTITA) = (
    SELECT MAX(TOTALE)
    FROM (
        SELECT SUM(D2.QUANTITA) AS TOTALE
        FROM DETTAGLIORDINE D2
        JOIN PRODOTTI P2 ON P2.ID = D2.ID_PROD
        GROUP BY P2.NOME_PRODOTTO
    ) t
);

SELECT MAX(TOTALE)
FROM(select
p.NOME_PRODOTTO,
sum(d.QUANTITA) as TOTALE
from DETTAGLIORDINE d
join prodotti p
on p.id=d.ID_PROD
group by p.NOME_PRODOTTO) AS T;

SELECT TOP 1  C.NOME, SUM(D.QUANTITA) AS TOTALE_ORDINI
FROM DETTAGLIORDINE D 
JOIN ORDINI O ON O.ID = D.ID_ORDINE 
JOIN CLIENTI C ON C.ID = O.CLIENTI_ID
GROUP BY C.NOME
ORDER BY TOTALE_ORDINI DESC



SELECT  C.NOME, SUM(D.PREZZOU * D.QUANTITA ) AS FATTURATO
FROM DETTAGLIORDINE D 
JOIN ORDINI O ON O.ID = D.ID_ORDINE 
JOIN CLIENTI C ON C.ID = O.CLIENTI_ID
GROUP BY C.NOME
ORDER BY FATTURATO DESC




CREATE TABLE CATEGORIE (
ID INT PRIMARY KEY IDENTITY(1,1),
CATEGORIA NVARCHAR(50),

);
*/


select * from CATEGORIE