
--CREAZIONE NUOVO DATABASE
CREATE DATABASE NEGOZIODB;
 --SERVE A SEPARARE I COMANDI COSì CHE NON VADANO IN CONTEMPORANEA
--USO IL DB

USE NEGOZIODB;


CREATE TABLE CLIENTI(
ID INT PRIMARY KEY IDENTITY(1,1), --AUTOINCREMENT DI 1 IN ID
NOME NVARCHAR(50) NOT NULL,
EMAIL NVARCHAR(50) NOT NULL UNIQUE, 
DATA_REGISTRAZIONE DATE DEFAULT GETDATE(), --SETTA LA DATA A NOW CON GETDATE()
TITOLO_DI_STUDIO_ID INT NOT NULL
);

CREATE TABLE TITOLI_STUDIO(
ID INT PRIMARY KEY IDENTITY(1,1),
TDS NVARCHAR(50) NOT NULL
);


--MODIFICA PER AGGIUNTA FK A TABELLA CLIENTE
ALTER TABLE CLIENTI ADD CONSTRAINT FK_CLI_TDS
     FOREIGN KEY (TITOLO_DI_STUDIO_ID) REFERENCES TITOLI_STUDIO (ID)
     
CREATE TABLE PRODOTTI(
ID INT PRIMARY KEY IDENTITY(1,1),
NOME_PRODOTTO NVARCHAR(50) NOT NULL,
PREZZO DECIMAL(10,2) NOT NULL CHECK(PREZZO > 0),  --IN DECIMAL I DUE NUMERI INDICANO10 CARATTERI E 2 DECIMALI, CHECK è UNA FUNZIONE CHE CI PERMETTE DI FARE UN CONTROLLO SU VALORE INSERITO
GIACENZA INT  NOT NULL
);


CREATE TABLE ORDINI(
ID INT PRIMARY KEY IDENTITY(1,1),
DATA_ORDINE DATETIME DEFAULT SYSDATETIME(), -- DATA DI SISTEMA ATTUALE
NUM_COLLI INT,
TOTALE DECIMAL(10,2),
INDIRIZZO_SPEDIZIONE NVARCHAR(100) NOT NULL,
CLIENTI_ID INT NOT NULL ,
PUNTO_VENDITA_ID NVARCHAR(100),
CONSTRAINT FK_ORD_CLI FOREIGN KEY (CLIENTI_ID) REFERENCES CLIENTI(ID)
);

CREATE TABLE DETTAGLIORDINE(
ID INT PRIMARY KEY IDENTITY(1,1),
QUANTITA INT NOT NULL,
PREZZOU  DECIMAL(10,2) NOT NULL,
ID_ORDINE INT NOT NULL,
ID_PROD INT NOT NULL,
CONSTRAINT FK_ORD_DETT FOREIGN KEY (ID_ORDINE) REFERENCES ORDINI(ID),
CONSTRAINT FK_PROD_DETT FOREIGN KEY (ID_PROD) REFERENCES PRODOTTI(ID)
);